### ISSUE TITLE
Implement clear tasks function

### ISSUE THREAD

**Issue by gy-szabo** [bencefarkas200/to-do#4]

**Comment by bencefarkas200** [comment]
To delete the completed tasks from the database when `Clear` button is clicked, we need to modify the `doneClear` function from this:

```
doneClear(){
        this.doneArray = [];
        this.isDoneArrayEmpty = true;
}
```
To this:

```
doneClear() {
    this.doneArray.forEach((task) => {
      this.taskService.deleteTask(task._id ?? '').subscribe(() => {
        this.doneArray = [];
        this.isDoneArrayEmpty = true;
      });
    });
  }
```
We can iterate trough `doneArray` and use the existing `deleteTask` function to delete completed tasks, and only if it's successful, we can do the rest (turn `doneArray` into empty array, change the value of the bool variable). This way we can avoid the front-end and the database to be out of sync.

**Comment by gy-szabo** [comment]
Your solution to syncing the client and the database is correct, however calling the server for each task would work, but it is not a good idea in terms of performance.

**Comment by bencefarkas200** [comment]
I tought about it too! I think we can solve this by checking every deleted task if it's the last in the array. If it is, we can execute the rest of the code.

**Comment by gy-szabo** [comment]
Just to to reflect on your idea, I'm not sure how checking the last element would help with the performance issue. True, resetting the array would happen only once, but I was thinking about something else.

You could modify the client code anyway you want, but if you are still calling the `deleteTask` endpoint on several elements, you will end up having the same performance issue. I'd suggest creating a new endpoint, that deletes each task that is done as well. This way the business logic is going to be on the server side, and the client will only have to call the server once instead of several times, which solves the aforementioned performance issue.
