### ISSUE TITLE
Write the README.md file

### ISSUE THREAD

**Issue by gy-szabo** [bencefarkas200/to-do#8]
A readme can set the context for any viewer that checks out this repo, and it gives an overview about the whole app.

A good readme should start with a summary, some word about the different services (frontend, backend, db), and possibly even the motivation for the app. (you can arrange these as you see fit)

Then the setup instructions for new users should follow. In our case how to start the docker environment and how to run the backend locally, creating `.env` files in 2 places, things like that

**Comment by bencefarkas200** [comment]
[README.md](https://github.com/bencefarkas200/to-do/files/14384519/README.md)

I'd like you to check this before I upload it. I think I've corrected all the faults you've mentioned.

**Comment by gy-szabo** [comment]
very cool!

The db part is not entirely correct though. You can run the app locally by starting the `database` docker container and the backend will be able to connect to the db without the need of installing mongodb. We should not tell people to install additional software, that's what docker is for.
